spring:

    datasource:
        url: jdbc:mysql://172.17.0.1:3306/oasisv2.0?serverTimezone=CTT&characterEncoding=UTF-8
        username: root
        password: root
        driver-class-name: com.mysql.cj.jdbc.Driver
        max-active: 200
        max-idle: 20
        min-idle: 10
    thymeleaf:
        cache: false
    jackson:
        time-zone: GMT+8
    application:
        name: author-client

mybatis:
    mapper-locations: classpath:dataImpl/*/*Mapper.xml
# mybatis 分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: "true"
    params: count=countSql


eureka:
    client:
        service-url:
            defaultZone: http://eurekaservice:8761/eureka/
server:
    port: 8088
